// <auto-generated />
using System;
using DPA.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DPA.Database.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20190414132702_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DPA.Model.ConstraintEntity", b =>
                {
                    b.Property<long>("ConstraintId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("EducationType");

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsFreeDay");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<DateTime>("UpdatedDate");

                    b.Property<long>("UserId");

                    b.Property<int>("WeeklyHour");

                    b.HasKey("ConstraintId");

                    b.HasIndex("UserId");

                    b.ToTable("Constraint","User");

                    b.HasData(
                        new
                        {
                            ConstraintId = 1L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 297, DateTimeKind.Local).AddTicks(1350),
                            Description = "Description",
                            EducationType = 1,
                            IsActive = true,
                            IsFreeDay = true,
                            Title = "Kısıt 1",
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 297, DateTimeKind.Local).AddTicks(1360),
                            UserId = 2L,
                            WeeklyHour = 4
                        },
                        new
                        {
                            ConstraintId = 2L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 297, DateTimeKind.Local).AddTicks(2370),
                            Description = "Description",
                            EducationType = 2,
                            IsActive = true,
                            IsFreeDay = true,
                            Title = "Kısıt 2",
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 297, DateTimeKind.Local).AddTicks(2370),
                            UserId = 3L,
                            WeeklyHour = 6
                        },
                        new
                        {
                            ConstraintId = 3L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 297, DateTimeKind.Local).AddTicks(2430),
                            Description = "Description",
                            EducationType = 3,
                            IsActive = true,
                            IsFreeDay = false,
                            Title = "Kısıt 3",
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 297, DateTimeKind.Local).AddTicks(2430),
                            UserId = 4L,
                            WeeklyHour = 8
                        },
                        new
                        {
                            ConstraintId = 4L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 297, DateTimeKind.Local).AddTicks(2470),
                            Description = "Description",
                            EducationType = 2,
                            IsActive = true,
                            IsFreeDay = true,
                            Title = "Kısıt 4",
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 297, DateTimeKind.Local).AddTicks(2470),
                            UserId = 5L,
                            WeeklyHour = 10
                        },
                        new
                        {
                            ConstraintId = 5L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 297, DateTimeKind.Local).AddTicks(2500),
                            Description = "Description",
                            EducationType = 1,
                            IsActive = true,
                            IsFreeDay = true,
                            Title = "Kısıt 5",
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 297, DateTimeKind.Local).AddTicks(2510),
                            UserId = 6L,
                            WeeklyHour = 12
                        },
                        new
                        {
                            ConstraintId = 6L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 297, DateTimeKind.Local).AddTicks(2540),
                            Description = "Description",
                            EducationType = 3,
                            IsActive = true,
                            IsFreeDay = false,
                            Title = "Kısıt 6",
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 297, DateTimeKind.Local).AddTicks(2550),
                            UserId = 7L,
                            WeeklyHour = 14
                        },
                        new
                        {
                            ConstraintId = 7L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 297, DateTimeKind.Local).AddTicks(2580),
                            Description = "Description",
                            EducationType = 2,
                            IsActive = true,
                            IsFreeDay = true,
                            Title = "Kısıt 7",
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 297, DateTimeKind.Local).AddTicks(2580),
                            UserId = 8L,
                            WeeklyHour = 8
                        },
                        new
                        {
                            ConstraintId = 8L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 297, DateTimeKind.Local).AddTicks(2620),
                            Description = "Description",
                            EducationType = 1,
                            IsActive = true,
                            IsFreeDay = true,
                            Title = "Kısıt 8",
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 297, DateTimeKind.Local).AddTicks(2620),
                            UserId = 9L,
                            WeeklyHour = 10
                        },
                        new
                        {
                            ConstraintId = 9L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 297, DateTimeKind.Local).AddTicks(2650),
                            Description = "Description",
                            EducationType = 3,
                            IsActive = true,
                            IsFreeDay = false,
                            Title = "Kısıt 9",
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 297, DateTimeKind.Local).AddTicks(2650),
                            UserId = 10L,
                            WeeklyHour = 12
                        },
                        new
                        {
                            ConstraintId = 10L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 297, DateTimeKind.Local).AddTicks(2680),
                            Description = "Description",
                            EducationType = 1,
                            IsActive = true,
                            IsFreeDay = true,
                            Title = "Kısıt 10",
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 297, DateTimeKind.Local).AddTicks(2690),
                            UserId = 11L,
                            WeeklyHour = 12
                        },
                        new
                        {
                            ConstraintId = 11L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 297, DateTimeKind.Local).AddTicks(2720),
                            Description = "Description",
                            EducationType = 2,
                            IsActive = true,
                            IsFreeDay = true,
                            Title = "Kısıt 11",
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 297, DateTimeKind.Local).AddTicks(2720),
                            UserId = 12L,
                            WeeklyHour = 12
                        },
                        new
                        {
                            ConstraintId = 12L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 297, DateTimeKind.Local).AddTicks(2750),
                            Description = "Description",
                            EducationType = 3,
                            IsActive = true,
                            IsFreeDay = false,
                            Title = "Kısıt 12",
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 297, DateTimeKind.Local).AddTicks(2750),
                            UserId = 13L,
                            WeeklyHour = 16
                        },
                        new
                        {
                            ConstraintId = 13L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 297, DateTimeKind.Local).AddTicks(2780),
                            Description = "Description",
                            EducationType = 3,
                            IsActive = true,
                            IsFreeDay = false,
                            Title = "Kısıt 13",
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 297, DateTimeKind.Local).AddTicks(2790),
                            UserId = 14L,
                            WeeklyHour = 16
                        });
                });

            modelBuilder.Entity("DPA.Model.DepartmentEntity", b =>
                {
                    b.Property<long>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("DepartmentCode")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<long>("FacultyId");

                    b.Property<long?>("HeadOfDepartmentId");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<DateTime>("UpdatedDate");

                    b.HasKey("DepartmentId");

                    b.HasIndex("FacultyId");

                    b.HasIndex("HeadOfDepartmentId")
                        .IsUnique()
                        .HasFilter("[HeadOfDepartmentId] IS NOT NULL");

                    b.ToTable("Department","Faculty");

                    b.HasData(
                        new
                        {
                            DepartmentId = 1L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 300, DateTimeKind.Local).AddTicks(280),
                            DepartmentCode = "BM310",
                            FacultyId = 1L,
                            HeadOfDepartmentId = 1L,
                            Title = "Bilgisayar Mühendisliği Bölümü",
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 300, DateTimeKind.Local).AddTicks(290)
                        },
                        new
                        {
                            DepartmentId = 2L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 300, DateTimeKind.Local).AddTicks(1490),
                            DepartmentCode = "BM311",
                            FacultyId = 1L,
                            Title = "Bilişim Sistemleri Mühendisliği Bölümü",
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 300, DateTimeKind.Local).AddTicks(1490)
                        },
                        new
                        {
                            DepartmentId = 3L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 300, DateTimeKind.Local).AddTicks(1530),
                            DepartmentCode = "BM312",
                            FacultyId = 1L,
                            Title = "Yazılım Mühendisliği Bölümü",
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 300, DateTimeKind.Local).AddTicks(1530)
                        });
                });

            modelBuilder.Entity("DPA.Model.DepartmentLessonEntity", b =>
                {
                    b.Property<long>("DepartmentLessonId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<long>("DepartmentId");

                    b.Property<long>("LessonId");

                    b.Property<DateTime>("UpdatedDate");

                    b.HasKey("DepartmentLessonId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("LessonId");

                    b.ToTable("DepartmentLesson","Faculty");

                    b.HasData(
                        new
                        {
                            DepartmentLessonId = 1L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 300, DateTimeKind.Local).AddTicks(3280),
                            DepartmentId = 1L,
                            LessonId = 1L,
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 300, DateTimeKind.Local).AddTicks(3290)
                        },
                        new
                        {
                            DepartmentLessonId = 2L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 300, DateTimeKind.Local).AddTicks(4070),
                            DepartmentId = 1L,
                            LessonId = 2L,
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 300, DateTimeKind.Local).AddTicks(4070)
                        },
                        new
                        {
                            DepartmentLessonId = 3L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 300, DateTimeKind.Local).AddTicks(4110),
                            DepartmentId = 1L,
                            LessonId = 3L,
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 300, DateTimeKind.Local).AddTicks(4110)
                        },
                        new
                        {
                            DepartmentLessonId = 4L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 300, DateTimeKind.Local).AddTicks(4140),
                            DepartmentId = 1L,
                            LessonId = 4L,
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 300, DateTimeKind.Local).AddTicks(4140)
                        },
                        new
                        {
                            DepartmentLessonId = 5L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 300, DateTimeKind.Local).AddTicks(4160),
                            DepartmentId = 1L,
                            LessonId = 5L,
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 300, DateTimeKind.Local).AddTicks(4170)
                        },
                        new
                        {
                            DepartmentLessonId = 6L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 300, DateTimeKind.Local).AddTicks(4230),
                            DepartmentId = 1L,
                            LessonId = 6L,
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 300, DateTimeKind.Local).AddTicks(4230)
                        },
                        new
                        {
                            DepartmentLessonId = 7L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 300, DateTimeKind.Local).AddTicks(4260),
                            DepartmentId = 1L,
                            LessonId = 7L,
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 300, DateTimeKind.Local).AddTicks(4260)
                        },
                        new
                        {
                            DepartmentLessonId = 8L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 300, DateTimeKind.Local).AddTicks(4290),
                            DepartmentId = 1L,
                            LessonId = 8L,
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 300, DateTimeKind.Local).AddTicks(4290)
                        },
                        new
                        {
                            DepartmentLessonId = 9L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 300, DateTimeKind.Local).AddTicks(4320),
                            DepartmentId = 1L,
                            LessonId = 9L,
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 300, DateTimeKind.Local).AddTicks(4320)
                        },
                        new
                        {
                            DepartmentLessonId = 10L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 300, DateTimeKind.Local).AddTicks(4350),
                            DepartmentId = 1L,
                            LessonId = 10L,
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 300, DateTimeKind.Local).AddTicks(4350)
                        },
                        new
                        {
                            DepartmentLessonId = 11L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 300, DateTimeKind.Local).AddTicks(4370),
                            DepartmentId = 1L,
                            LessonId = 11L,
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 300, DateTimeKind.Local).AddTicks(4370)
                        },
                        new
                        {
                            DepartmentLessonId = 12L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 300, DateTimeKind.Local).AddTicks(4400),
                            DepartmentId = 1L,
                            LessonId = 12L,
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 300, DateTimeKind.Local).AddTicks(4400)
                        });
                });

            modelBuilder.Entity("DPA.Model.FacultyEntity", b =>
                {
                    b.Property<long>("FacultyId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("FacultyCode")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<DateTime>("UpdatedDate");

                    b.HasKey("FacultyId");

                    b.ToTable("Faculty","Faculty");

                    b.HasData(
                        new
                        {
                            FacultyId = 1L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 299, DateTimeKind.Local).AddTicks(5450),
                            FacultyCode = "BM310",
                            Title = "BİLGİSAYAR VE BİLİŞİM BİLİMLERİ FAKÜLTESİ",
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 299, DateTimeKind.Local).AddTicks(5460)
                        },
                        new
                        {
                            FacultyId = 2L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 299, DateTimeKind.Local).AddTicks(5720),
                            FacultyCode = "MF123",
                            Title = "Mühendislik Fakültesi",
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 299, DateTimeKind.Local).AddTicks(5730)
                        },
                        new
                        {
                            FacultyId = 3L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 299, DateTimeKind.Local).AddTicks(5760),
                            FacultyCode = "HKK112",
                            Title = "Hukuk Fakültesi",
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 299, DateTimeKind.Local).AddTicks(5760)
                        },
                        new
                        {
                            FacultyId = 4L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 299, DateTimeKind.Local).AddTicks(5790),
                            FacultyCode = "TKL423",
                            Title = "Teknoloji Fakültesi",
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 299, DateTimeKind.Local).AddTicks(5790)
                        });
                });

            modelBuilder.Entity("DPA.Model.LessonEntity", b =>
                {
                    b.Property<long>("LessonId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AKTS");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<int>("Credit");

                    b.Property<string>("LessonCode")
                        .IsRequired();

                    b.Property<int>("LessonType");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<int>("SemesterType");

                    b.Property<DateTime>("UpdatedDate");

                    b.Property<int>("WeeklyHour");

                    b.HasKey("LessonId");

                    b.ToTable("Lesson","Faculty");

                    b.HasData(
                        new
                        {
                            LessonId = 1L,
                            AKTS = 4,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 298, DateTimeKind.Local).AddTicks(220),
                            Credit = 4,
                            LessonCode = "TUR 101",
                            LessonType = 1,
                            Name = "TÜRK DİLİ",
                            SemesterType = 1,
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 298, DateTimeKind.Local).AddTicks(240),
                            WeeklyHour = 4
                        },
                        new
                        {
                            LessonId = 2L,
                            AKTS = 6,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 298, DateTimeKind.Local).AddTicks(2500),
                            Credit = 4,
                            LessonCode = "FIZ 111",
                            LessonType = 1,
                            Name = "FİZİK I",
                            SemesterType = 1,
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 298, DateTimeKind.Local).AddTicks(2500),
                            WeeklyHour = 5
                        },
                        new
                        {
                            LessonId = 3L,
                            AKTS = 6,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 298, DateTimeKind.Local).AddTicks(2560),
                            Credit = 4,
                            LessonCode = "MAT 111",
                            LessonType = 1,
                            Name = "MATEMATİK I",
                            SemesterType = 1,
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 298, DateTimeKind.Local).AddTicks(2570),
                            WeeklyHour = 4
                        },
                        new
                        {
                            LessonId = 4L,
                            AKTS = 4,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 298, DateTimeKind.Local).AddTicks(2600),
                            Credit = 2,
                            LessonCode = "MAT 113",
                            LessonType = 1,
                            Name = "LİNEER CEBİR",
                            SemesterType = 1,
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 298, DateTimeKind.Local).AddTicks(2610),
                            WeeklyHour = 2
                        },
                        new
                        {
                            LessonId = 5L,
                            AKTS = 4,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 298, DateTimeKind.Local).AddTicks(2640),
                            Credit = 2,
                            LessonCode = "BSM 101",
                            LessonType = 1,
                            Name = "BİLGİSAYAR MÜHENDİSLİĞİNE GİRİŞ",
                            SemesterType = 1,
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 298, DateTimeKind.Local).AddTicks(2640),
                            WeeklyHour = 2
                        },
                        new
                        {
                            LessonId = 6L,
                            AKTS = 6,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 298, DateTimeKind.Local).AddTicks(2680),
                            Credit = 4,
                            LessonCode = "BSM 103",
                            LessonType = 1,
                            Name = "PROGRAMLAMAYA GİRİŞ",
                            SemesterType = 1,
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 298, DateTimeKind.Local).AddTicks(2690),
                            WeeklyHour = 4
                        },
                        new
                        {
                            LessonId = 7L,
                            AKTS = 4,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 298, DateTimeKind.Local).AddTicks(2720),
                            Credit = 4,
                            LessonCode = "ING 190",
                            LessonType = 1,
                            Name = "İNGİLİZCE",
                            SemesterType = 2,
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 298, DateTimeKind.Local).AddTicks(2720),
                            WeeklyHour = 4
                        },
                        new
                        {
                            LessonId = 8L,
                            AKTS = 6,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 298, DateTimeKind.Local).AddTicks(2770),
                            Credit = 4,
                            LessonCode = "FIZ 112",
                            LessonType = 1,
                            Name = "FİZİK II",
                            SemesterType = 2,
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 298, DateTimeKind.Local).AddTicks(2780),
                            WeeklyHour = 5
                        },
                        new
                        {
                            LessonId = 9L,
                            AKTS = 6,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 298, DateTimeKind.Local).AddTicks(2810),
                            Credit = 4,
                            LessonCode = "MAT 112",
                            LessonType = 1,
                            Name = "MATEMATİK II",
                            SemesterType = 2,
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 298, DateTimeKind.Local).AddTicks(2810),
                            WeeklyHour = 4
                        },
                        new
                        {
                            LessonId = 10L,
                            AKTS = 6,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 298, DateTimeKind.Local).AddTicks(2850),
                            Credit = 4,
                            LessonCode = "BSM 102",
                            LessonType = 1,
                            Name = "NESNEYE DAYALI PROGRAMLAMA",
                            SemesterType = 2,
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 298, DateTimeKind.Local).AddTicks(2850),
                            WeeklyHour = 4
                        },
                        new
                        {
                            LessonId = 11L,
                            AKTS = 4,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 298, DateTimeKind.Local).AddTicks(2890),
                            Credit = 3,
                            LessonCode = "BSM 104",
                            LessonType = 1,
                            Name = "WEB TEKNOLOJİLERİ",
                            SemesterType = 2,
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 298, DateTimeKind.Local).AddTicks(2890),
                            WeeklyHour = 3
                        },
                        new
                        {
                            LessonId = 12L,
                            AKTS = 4,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 298, DateTimeKind.Local).AddTicks(2930),
                            Credit = 3,
                            LessonCode = "IST 108",
                            LessonType = 1,
                            Name = "OLASILIK VE İSTATİSTİK",
                            SemesterType = 2,
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 298, DateTimeKind.Local).AddTicks(2930),
                            WeeklyHour = 3
                        });
                });

            modelBuilder.Entity("DPA.Model.LessonGroupEntity", b =>
                {
                    b.Property<long>("LessonGroupId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<int>("GroupType");

                    b.Property<long>("LessonId");

                    b.Property<DateTime>("UpdatedDate");

                    b.HasKey("LessonGroupId");

                    b.HasIndex("LessonId");

                    b.ToTable("LessonGroup","Faculty");

                    b.HasData(
                        new
                        {
                            LessonGroupId = 1L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 298, DateTimeKind.Local).AddTicks(5610),
                            GroupType = 1,
                            LessonId = 1L,
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 298, DateTimeKind.Local).AddTicks(5620)
                        },
                        new
                        {
                            LessonGroupId = 2L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 298, DateTimeKind.Local).AddTicks(5910),
                            GroupType = 2,
                            LessonId = 1L,
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 298, DateTimeKind.Local).AddTicks(5920)
                        },
                        new
                        {
                            LessonGroupId = 3L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 298, DateTimeKind.Local).AddTicks(5960),
                            GroupType = 1,
                            LessonId = 2L,
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 298, DateTimeKind.Local).AddTicks(5960)
                        },
                        new
                        {
                            LessonGroupId = 4L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 298, DateTimeKind.Local).AddTicks(5990),
                            GroupType = 2,
                            LessonId = 2L,
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 298, DateTimeKind.Local).AddTicks(5990)
                        },
                        new
                        {
                            LessonGroupId = 5L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 298, DateTimeKind.Local).AddTicks(6020),
                            GroupType = 1,
                            LessonId = 3L,
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 298, DateTimeKind.Local).AddTicks(6030)
                        },
                        new
                        {
                            LessonGroupId = 6L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 298, DateTimeKind.Local).AddTicks(6060),
                            GroupType = 2,
                            LessonId = 3L,
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 298, DateTimeKind.Local).AddTicks(6060)
                        },
                        new
                        {
                            LessonGroupId = 7L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 298, DateTimeKind.Local).AddTicks(6100),
                            GroupType = 1,
                            LessonId = 4L,
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 298, DateTimeKind.Local).AddTicks(6100)
                        },
                        new
                        {
                            LessonGroupId = 8L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 298, DateTimeKind.Local).AddTicks(6130),
                            GroupType = 1,
                            LessonId = 5L,
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 298, DateTimeKind.Local).AddTicks(6130)
                        },
                        new
                        {
                            LessonGroupId = 9L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 298, DateTimeKind.Local).AddTicks(6160),
                            GroupType = 1,
                            LessonId = 6L,
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 298, DateTimeKind.Local).AddTicks(6160)
                        },
                        new
                        {
                            LessonGroupId = 10L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 298, DateTimeKind.Local).AddTicks(6200),
                            GroupType = 2,
                            LessonId = 6L,
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 298, DateTimeKind.Local).AddTicks(6200)
                        },
                        new
                        {
                            LessonGroupId = 11L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 298, DateTimeKind.Local).AddTicks(6230),
                            GroupType = 1,
                            LessonId = 7L,
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 298, DateTimeKind.Local).AddTicks(6230)
                        },
                        new
                        {
                            LessonGroupId = 12L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 298, DateTimeKind.Local).AddTicks(6260),
                            GroupType = 2,
                            LessonId = 7L,
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 298, DateTimeKind.Local).AddTicks(6260)
                        },
                        new
                        {
                            LessonGroupId = 13L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 298, DateTimeKind.Local).AddTicks(6290),
                            GroupType = 1,
                            LessonId = 8L,
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 298, DateTimeKind.Local).AddTicks(6290)
                        },
                        new
                        {
                            LessonGroupId = 14L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 298, DateTimeKind.Local).AddTicks(6320),
                            GroupType = 2,
                            LessonId = 8L,
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 298, DateTimeKind.Local).AddTicks(6330)
                        },
                        new
                        {
                            LessonGroupId = 15L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 298, DateTimeKind.Local).AddTicks(6350),
                            GroupType = 1,
                            LessonId = 9L,
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 298, DateTimeKind.Local).AddTicks(6360)
                        },
                        new
                        {
                            LessonGroupId = 16L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 298, DateTimeKind.Local).AddTicks(6390),
                            GroupType = 2,
                            LessonId = 9L,
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 298, DateTimeKind.Local).AddTicks(6390)
                        },
                        new
                        {
                            LessonGroupId = 17L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 298, DateTimeKind.Local).AddTicks(6420),
                            GroupType = 1,
                            LessonId = 10L,
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 298, DateTimeKind.Local).AddTicks(6420)
                        },
                        new
                        {
                            LessonGroupId = 18L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 298, DateTimeKind.Local).AddTicks(6470),
                            GroupType = 2,
                            LessonId = 10L,
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 298, DateTimeKind.Local).AddTicks(6470)
                        },
                        new
                        {
                            LessonGroupId = 19L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 298, DateTimeKind.Local).AddTicks(6510),
                            GroupType = 1,
                            LessonId = 11L,
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 298, DateTimeKind.Local).AddTicks(6510)
                        },
                        new
                        {
                            LessonGroupId = 20L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 298, DateTimeKind.Local).AddTicks(6540),
                            GroupType = 2,
                            LessonId = 11L,
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 298, DateTimeKind.Local).AddTicks(6540)
                        },
                        new
                        {
                            LessonGroupId = 21L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 298, DateTimeKind.Local).AddTicks(6570),
                            GroupType = 1,
                            LessonId = 12L,
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 298, DateTimeKind.Local).AddTicks(6580)
                        },
                        new
                        {
                            LessonGroupId = 22L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 298, DateTimeKind.Local).AddTicks(6610),
                            GroupType = 2,
                            LessonId = 12L,
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 298, DateTimeKind.Local).AddTicks(6610)
                        });
                });

            modelBuilder.Entity("DPA.Model.LocationEntity", b =>
                {
                    b.Property<long>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<long>("FacultyId");

                    b.Property<string>("Title")
                        .IsRequired();

                    b.Property<DateTime>("UpdatedDate");

                    b.HasKey("LocationId");

                    b.HasIndex("FacultyId");

                    b.ToTable("Location","Faculty");

                    b.HasData(
                        new
                        {
                            LocationId = 1L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 300, DateTimeKind.Local).AddTicks(6720),
                            FacultyId = 1L,
                            Title = "1000",
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 300, DateTimeKind.Local).AddTicks(6730)
                        },
                        new
                        {
                            LocationId = 2L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 300, DateTimeKind.Local).AddTicks(7530),
                            FacultyId = 1L,
                            Title = "1001",
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 300, DateTimeKind.Local).AddTicks(7530)
                        },
                        new
                        {
                            LocationId = 3L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 300, DateTimeKind.Local).AddTicks(7570),
                            FacultyId = 1L,
                            Title = "1002",
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 300, DateTimeKind.Local).AddTicks(7580)
                        },
                        new
                        {
                            LocationId = 4L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 300, DateTimeKind.Local).AddTicks(7610),
                            FacultyId = 1L,
                            Title = "1003",
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 300, DateTimeKind.Local).AddTicks(7610)
                        },
                        new
                        {
                            LocationId = 5L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 300, DateTimeKind.Local).AddTicks(7640),
                            FacultyId = 1L,
                            Title = "1004",
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 300, DateTimeKind.Local).AddTicks(7640)
                        },
                        new
                        {
                            LocationId = 6L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 300, DateTimeKind.Local).AddTicks(7670),
                            FacultyId = 1L,
                            Title = "1005",
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 300, DateTimeKind.Local).AddTicks(7670)
                        },
                        new
                        {
                            LocationId = 7L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 300, DateTimeKind.Local).AddTicks(7700),
                            FacultyId = 1L,
                            Title = "1006",
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 300, DateTimeKind.Local).AddTicks(7710)
                        },
                        new
                        {
                            LocationId = 8L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 300, DateTimeKind.Local).AddTicks(7730),
                            FacultyId = 1L,
                            Title = "1007",
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 300, DateTimeKind.Local).AddTicks(7740)
                        },
                        new
                        {
                            LocationId = 9L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 300, DateTimeKind.Local).AddTicks(7760),
                            FacultyId = 1L,
                            Title = "1008",
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 300, DateTimeKind.Local).AddTicks(7770)
                        },
                        new
                        {
                            LocationId = 10L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 300, DateTimeKind.Local).AddTicks(7800),
                            FacultyId = 1L,
                            Title = "1009",
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 300, DateTimeKind.Local).AddTicks(7800)
                        },
                        new
                        {
                            LocationId = 11L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 300, DateTimeKind.Local).AddTicks(7830),
                            FacultyId = 1L,
                            Title = "10010",
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 300, DateTimeKind.Local).AddTicks(7830)
                        },
                        new
                        {
                            LocationId = 12L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 300, DateTimeKind.Local).AddTicks(7860),
                            FacultyId = 1L,
                            Title = "10011",
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 300, DateTimeKind.Local).AddTicks(7860)
                        },
                        new
                        {
                            LocationId = 13L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 300, DateTimeKind.Local).AddTicks(7890),
                            FacultyId = 1L,
                            Title = "10012",
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 300, DateTimeKind.Local).AddTicks(7890)
                        },
                        new
                        {
                            LocationId = 14L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 300, DateTimeKind.Local).AddTicks(7910),
                            FacultyId = 1L,
                            Title = "10013",
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 300, DateTimeKind.Local).AddTicks(7920)
                        },
                        new
                        {
                            LocationId = 15L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 300, DateTimeKind.Local).AddTicks(7940),
                            FacultyId = 1L,
                            Title = "10014",
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 300, DateTimeKind.Local).AddTicks(7950)
                        },
                        new
                        {
                            LocationId = 16L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 300, DateTimeKind.Local).AddTicks(7970),
                            FacultyId = 1L,
                            Title = "10015",
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 300, DateTimeKind.Local).AddTicks(7980)
                        },
                        new
                        {
                            LocationId = 17L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 300, DateTimeKind.Local).AddTicks(8000),
                            FacultyId = 1L,
                            Title = "10016",
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 300, DateTimeKind.Local).AddTicks(8010)
                        },
                        new
                        {
                            LocationId = 18L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 300, DateTimeKind.Local).AddTicks(8050),
                            FacultyId = 1L,
                            Title = "10017",
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 300, DateTimeKind.Local).AddTicks(8050)
                        });
                });

            modelBuilder.Entity("DPA.Model.SyllabusEntity", b =>
                {
                    b.Property<long>("SyllabusId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<long>("DepartmentId");

                    b.Property<int>("EducationType");

                    b.Property<int>("PeriodType");

                    b.Property<int>("SemesterType");

                    b.Property<DateTime>("UpdatedDate");

                    b.Property<int>("Year");

                    b.HasKey("SyllabusId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Syllabus","Syllabus");
                });

            modelBuilder.Entity("DPA.Model.TimeEntity", b =>
                {
                    b.Property<long>("TimeId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<int>("DayOfTheWeek");

                    b.Property<int>("EndTime");

                    b.Property<int>("StarTime");

                    b.Property<long>("UnitLessonId");

                    b.Property<DateTime>("UpdatedDate");

                    b.HasKey("TimeId");

                    b.HasIndex("UnitLessonId");

                    b.ToTable("Time","Syllabus");
                });

            modelBuilder.Entity("DPA.Model.UnitLessonEntity", b =>
                {
                    b.Property<long>("UnitLessonId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<long>("LessonId");

                    b.Property<long>("LocationId");

                    b.Property<long>("SyllabusId");

                    b.Property<DateTime>("UpdatedDate");

                    b.Property<long>("UserId");

                    b.HasKey("UnitLessonId");

                    b.HasIndex("LessonId");

                    b.HasIndex("UserId");

                    b.ToTable("UnitLesson","Syllabus");
                });

            modelBuilder.Entity("DPA.Model.UserEntity", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(300);

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<int>("Roles");

                    b.Property<int>("Status");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<int>("Title");

                    b.Property<DateTime>("UpdatedDate");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("User","User");

                    b.HasData(
                        new
                        {
                            UserId = 1L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 293, DateTimeKind.Local).AddTicks(3590),
                            Email = "administrator@administrator.com",
                            Login = "1h0ATANFe6x7kMHo1PURE74WI0ayevUwfK/+Ie+IWX/xWrFWngcVUwL/ewryn38EMVMQBFaNo4SaVwgXaBWnDw==",
                            Name = "Administrator",
                            Password = "CkcVGgdOYzq3tr7Wqrckq73c0yUPgKBrxhKiM6kHgFEB8kQbWykm5UzorIz7wHS7elZ0iDBIffCVkdvhZ+gA9g==",
                            Roles = 3,
                            Status = 1,
                            Surname = "Administrator",
                            Title = 0,
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 293, DateTimeKind.Local).AddTicks(3630)
                        },
                        new
                        {
                            UserId = 2L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 296, DateTimeKind.Local).AddTicks(3460),
                            Email = "celalceken@sakarya.edu.tr",
                            Login = "sqqdGm+QyoYM0p0Co1hgYX9aPayWbuCoIpPkN3vm+ntuFm8/mNW901g1mPJP0V/ZdOuD05U5btfuffNNkvRSMQ==",
                            Name = "Celal",
                            Password = "CkcVGgdOYzq3tr7Wqrckq73c0yUPgKBrxhKiM6kHgFEB8kQbWykm5UzorIz7wHS7elZ0iDBIffCVkdvhZ+gA9g==",
                            Roles = 1,
                            Status = 1,
                            Surname = "Çeken",
                            Title = 1,
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 296, DateTimeKind.Local).AddTicks(3470)
                        },
                        new
                        {
                            UserId = 3L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 296, DateTimeKind.Local).AddTicks(3770),
                            Email = "coz@sakarya.edu.tr",
                            Login = "lpe17pCaWVWNiI8dXvCHIEgaSpoTiULAZbWhSDxk1zbEdv3je87szjOl8CFst+hU8hITlcCc2AtvEIAdxgA+ng==",
                            Name = "Cemil",
                            Password = "CkcVGgdOYzq3tr7Wqrckq73c0yUPgKBrxhKiM6kHgFEB8kQbWykm5UzorIz7wHS7elZ0iDBIffCVkdvhZ+gA9g==",
                            Roles = 2,
                            Status = 1,
                            Surname = "Öz",
                            Title = 1,
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 296, DateTimeKind.Local).AddTicks(3770)
                        },
                        new
                        {
                            UserId = 4L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 296, DateTimeKind.Local).AddTicks(3910),
                            Email = "umit@sakarya.edu.tr",
                            Login = "aYoce2dux8eT5/nvryziC97/nrEiqS5+S0hEMEvKhB0fGnI8dbF7AFLAi/+6dnvNOZwnHDJi+9VQwUtKaPeEcA==",
                            Name = "Ümit",
                            Password = "CkcVGgdOYzq3tr7Wqrckq73c0yUPgKBrxhKiM6kHgFEB8kQbWykm5UzorIz7wHS7elZ0iDBIffCVkdvhZ+gA9g==",
                            Roles = 1,
                            Status = 1,
                            Surname = "Kocabıçak",
                            Title = 1,
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 296, DateTimeKind.Local).AddTicks(3910)
                        },
                        new
                        {
                            UserId = 5L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 296, DateTimeKind.Local).AddTicks(4050),
                            Email = "azengin@sakarya.edu.tr",
                            Login = "3b8hL6Cd/mm0v6MgNvkKvnoUjLbK/8+JNw/0AIXmtZjxfOcpZYndmXqV8UHH4dI8b1EnJ4LZWNs8lQV74pv2jQ==",
                            Name = "Ahmet",
                            Password = "CkcVGgdOYzq3tr7Wqrckq73c0yUPgKBrxhKiM6kHgFEB8kQbWykm5UzorIz7wHS7elZ0iDBIffCVkdvhZ+gA9g==",
                            Roles = 1,
                            Status = 1,
                            Surname = "Zengin",
                            Title = 3,
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 296, DateTimeKind.Local).AddTicks(4050)
                        },
                        new
                        {
                            UserId = 6L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 296, DateTimeKind.Local).AddTicks(4180),
                            Email = "ozmen@sakarya.edu.tr",
                            Login = "DQFv5btLPxS0XrNFtrqeFiKSgPMPHwmrdk88CVFWmRBn2jK6vVpms4u8MoLUCvNMEhI99ECRDR8Rh6kuwDy+Zg==",
                            Name = "Ahmet",
                            Password = "CkcVGgdOYzq3tr7Wqrckq73c0yUPgKBrxhKiM6kHgFEB8kQbWykm5UzorIz7wHS7elZ0iDBIffCVkdvhZ+gA9g==",
                            Roles = 1,
                            Status = 1,
                            Surname = "Özmen",
                            Title = 3,
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 296, DateTimeKind.Local).AddTicks(4190)
                        },
                        new
                        {
                            UserId = 7L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 296, DateTimeKind.Local).AddTicks(4300),
                            Email = "cbayilmis@sakarya.edu.tr",
                            Login = "dOGHhzh1rEnqFOee38OOgEWmQM5Ex3+PtVwdLHWpKNlAjyuX+Zx9m91+f4TmlpEZKHL1hK/SunceSqkZ+m/u2g==",
                            Name = "Cüneyt",
                            Password = "CkcVGgdOYzq3tr7Wqrckq73c0yUPgKBrxhKiM6kHgFEB8kQbWykm5UzorIz7wHS7elZ0iDBIffCVkdvhZ+gA9g==",
                            Roles = 1,
                            Status = 1,
                            Surname = "Bayılmış",
                            Title = 3,
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 296, DateTimeKind.Local).AddTicks(4300)
                        },
                        new
                        {
                            UserId = 8L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 296, DateTimeKind.Local).AddTicks(4410),
                            Email = "ahmetarslan@sakarya.edu.tr",
                            Login = "h0g/LYGJK7QP9Lo3ZNMnCtlyzkVTVhf3c+S+lA7ExZ/U9XP+84SvRNjjmnYrCMKQS2r6D7TPuuHH75zNwTU4YQ==",
                            Name = "Ahmet",
                            Password = "CkcVGgdOYzq3tr7Wqrckq73c0yUPgKBrxhKiM6kHgFEB8kQbWykm5UzorIz7wHS7elZ0iDBIffCVkdvhZ+gA9g==",
                            Roles = 1,
                            Status = 1,
                            Surname = "Arslan",
                            Title = 2,
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 296, DateTimeKind.Local).AddTicks(4420)
                        },
                        new
                        {
                            UserId = 9L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 296, DateTimeKind.Local).AddTicks(4530),
                            Email = "beken@sakarya.edu.tr",
                            Login = "1J8MNqnuIyH/yRYMDQUejip91vrhoW+A3YdeD9eAYDtLuWx17l706wt6sXrzabpaW6CePiIxw5YU8jDQqnhMmA==",
                            Name = "Beyza",
                            Password = "CkcVGgdOYzq3tr7Wqrckq73c0yUPgKBrxhKiM6kHgFEB8kQbWykm5UzorIz7wHS7elZ0iDBIffCVkdvhZ+gA9g==",
                            Roles = 1,
                            Status = 1,
                            Surname = "Eken",
                            Title = 2,
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 296, DateTimeKind.Local).AddTicks(4530)
                        },
                        new
                        {
                            UserId = 10L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 296, DateTimeKind.Local).AddTicks(4660),
                            Email = "ddural@sakarya.edu.tr",
                            Login = "+tqmuZBVWUcLTVBaSyXnHUGxLiN8+kdgrkW2Ds9wxhS4wAC/NO+vSPFKLYoWHkZDvtP6gVUSfW77X9FkB/Bimw==",
                            Name = "Deniz",
                            Password = "CkcVGgdOYzq3tr7Wqrckq73c0yUPgKBrxhKiM6kHgFEB8kQbWykm5UzorIz7wHS7elZ0iDBIffCVkdvhZ+gA9g==",
                            Roles = 1,
                            Status = 1,
                            Surname = "Balta",
                            Title = 2,
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 296, DateTimeKind.Local).AddTicks(4670)
                        },
                        new
                        {
                            UserId = 11L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 296, DateTimeKind.Local).AddTicks(4780),
                            Email = "oguz@sakarya.edu.tr",
                            Login = "N2dbG766DJ+GQaFDlEPrH3ioi+ZD9VpnVGVHCtTxZl9nC+ruFrcTi7zgOIydZKCFaBqwKxpowNV2GYBRSPvNbQ==",
                            Name = "Oguzhan",
                            Password = "CkcVGgdOYzq3tr7Wqrckq73c0yUPgKBrxhKiM6kHgFEB8kQbWykm5UzorIz7wHS7elZ0iDBIffCVkdvhZ+gA9g==",
                            Roles = 1,
                            Status = 1,
                            Surname = "Aydın",
                            Title = 4,
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 296, DateTimeKind.Local).AddTicks(4780)
                        },
                        new
                        {
                            UserId = 12L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 296, DateTimeKind.Local).AddTicks(4890),
                            Email = "hasantutan@sakarya.edu.tr",
                            Login = "GgWLS/9l9VKx7d18VXX+K3i3oJ6emqeCCniMnl6Gbg1cJftNXfCWUFao5OpNTaWCw39B/Z/1E5vV2+PPDFFesQ==",
                            Name = "Hasan",
                            Password = "CkcVGgdOYzq3tr7Wqrckq73c0yUPgKBrxhKiM6kHgFEB8kQbWykm5UzorIz7wHS7elZ0iDBIffCVkdvhZ+gA9g==",
                            Roles = 1,
                            Status = 1,
                            Surname = "Tutan",
                            Title = 4,
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 296, DateTimeKind.Local).AddTicks(4900)
                        },
                        new
                        {
                            UserId = 13L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 296, DateTimeKind.Local).AddTicks(5010),
                            Email = "ercanpala@sakarya.edu.tr",
                            Login = "PS+3mJHvWnYUHEhmnfo8APwTthPB92Bf2CDAupt1vAWgbc78SYmxb+wL48kZAUB6jHANlNfpH9yuAjRAyF6vlA==",
                            Name = "Ercan",
                            Password = "CkcVGgdOYzq3tr7Wqrckq73c0yUPgKBrxhKiM6kHgFEB8kQbWykm5UzorIz7wHS7elZ0iDBIffCVkdvhZ+gA9g==",
                            Roles = 1,
                            Status = 1,
                            Surname = "Palabıyık",
                            Title = 4,
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 296, DateTimeKind.Local).AddTicks(5010)
                        },
                        new
                        {
                            UserId = 14L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 296, DateTimeKind.Local).AddTicks(5130),
                            Email = "meltemayy@sakarya.edu.tr",
                            Login = "Ee6akHsxZOrmTyxqSHZL9vRY+MZdM6mUeRwEc7K+dRE8k1k0qagjmU8MN7KF0yVy7EkplM/ZIx90EbzYa4vTdA==",
                            Name = "Meltem",
                            Password = "CkcVGgdOYzq3tr7Wqrckq73c0yUPgKBrxhKiM6kHgFEB8kQbWykm5UzorIz7wHS7elZ0iDBIffCVkdvhZ+gA9g==",
                            Roles = 1,
                            Status = 1,
                            Surname = "Aydın",
                            Title = 4,
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 296, DateTimeKind.Local).AddTicks(5140)
                        });
                });

            modelBuilder.Entity("DPA.Model.UserLessonEntity", b =>
                {
                    b.Property<long>("UserLessonId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<long>("LessonId");

                    b.Property<DateTime>("UpdatedDate");

                    b.Property<long>("UserId");

                    b.HasKey("UserLessonId");

                    b.HasIndex("LessonId");

                    b.HasIndex("UserId");

                    b.ToTable("UserLesson","User");

                    b.HasData(
                        new
                        {
                            UserLessonId = 1L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 298, DateTimeKind.Local).AddTicks(8630),
                            LessonId = 1L,
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 298, DateTimeKind.Local).AddTicks(8640),
                            UserId = 5L
                        },
                        new
                        {
                            UserLessonId = 2L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 298, DateTimeKind.Local).AddTicks(9550),
                            LessonId = 1L,
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 298, DateTimeKind.Local).AddTicks(9560),
                            UserId = 8L
                        },
                        new
                        {
                            UserLessonId = 3L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 298, DateTimeKind.Local).AddTicks(9600),
                            LessonId = 1L,
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 298, DateTimeKind.Local).AddTicks(9600),
                            UserId = 11L
                        },
                        new
                        {
                            UserLessonId = 4L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 298, DateTimeKind.Local).AddTicks(9640),
                            LessonId = 2L,
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 298, DateTimeKind.Local).AddTicks(9640),
                            UserId = 2L
                        },
                        new
                        {
                            UserLessonId = 5L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 298, DateTimeKind.Local).AddTicks(9670),
                            LessonId = 2L,
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 298, DateTimeKind.Local).AddTicks(9670),
                            UserId = 9L
                        },
                        new
                        {
                            UserLessonId = 6L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 298, DateTimeKind.Local).AddTicks(9710),
                            LessonId = 2L,
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 298, DateTimeKind.Local).AddTicks(9710),
                            UserId = 12L
                        },
                        new
                        {
                            UserLessonId = 7L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 298, DateTimeKind.Local).AddTicks(9740),
                            LessonId = 3L,
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 298, DateTimeKind.Local).AddTicks(9740),
                            UserId = 3L
                        },
                        new
                        {
                            UserLessonId = 8L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 298, DateTimeKind.Local).AddTicks(9770),
                            LessonId = 3L,
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 298, DateTimeKind.Local).AddTicks(9770),
                            UserId = 5L
                        },
                        new
                        {
                            UserLessonId = 9L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 298, DateTimeKind.Local).AddTicks(9800),
                            LessonId = 3L,
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 298, DateTimeKind.Local).AddTicks(9810),
                            UserId = 13L
                        },
                        new
                        {
                            UserLessonId = 10L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 298, DateTimeKind.Local).AddTicks(9840),
                            LessonId = 4L,
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 298, DateTimeKind.Local).AddTicks(9840),
                            UserId = 14L
                        },
                        new
                        {
                            UserLessonId = 11L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 298, DateTimeKind.Local).AddTicks(9870),
                            LessonId = 5L,
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 298, DateTimeKind.Local).AddTicks(9870),
                            UserId = 7L
                        },
                        new
                        {
                            UserLessonId = 12L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 298, DateTimeKind.Local).AddTicks(9900),
                            LessonId = 6L,
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 298, DateTimeKind.Local).AddTicks(9910),
                            UserId = 4L
                        },
                        new
                        {
                            UserLessonId = 13L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 298, DateTimeKind.Local).AddTicks(9930),
                            LessonId = 6L,
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 298, DateTimeKind.Local).AddTicks(9940),
                            UserId = 10L
                        },
                        new
                        {
                            UserLessonId = 14L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 298, DateTimeKind.Local).AddTicks(9970),
                            LessonId = 7L,
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 298, DateTimeKind.Local).AddTicks(9970),
                            UserId = 11L
                        },
                        new
                        {
                            UserLessonId = 15L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 299, DateTimeKind.Local),
                            LessonId = 7L,
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 299, DateTimeKind.Local),
                            UserId = 12L
                        },
                        new
                        {
                            UserLessonId = 16L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 299, DateTimeKind.Local).AddTicks(30),
                            LessonId = 7L,
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 299, DateTimeKind.Local).AddTicks(30),
                            UserId = 10L
                        },
                        new
                        {
                            UserLessonId = 17L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 299, DateTimeKind.Local).AddTicks(60),
                            LessonId = 8L,
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 299, DateTimeKind.Local).AddTicks(60),
                            UserId = 5L
                        },
                        new
                        {
                            UserLessonId = 18L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 299, DateTimeKind.Local).AddTicks(90),
                            LessonId = 8L,
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 299, DateTimeKind.Local).AddTicks(100),
                            UserId = 13L
                        },
                        new
                        {
                            UserLessonId = 19L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 299, DateTimeKind.Local).AddTicks(130),
                            LessonId = 9L,
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 299, DateTimeKind.Local).AddTicks(130),
                            UserId = 8L
                        },
                        new
                        {
                            UserLessonId = 20L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 299, DateTimeKind.Local).AddTicks(160),
                            LessonId = 9L,
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 299, DateTimeKind.Local).AddTicks(160),
                            UserId = 9L
                        },
                        new
                        {
                            UserLessonId = 21L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 299, DateTimeKind.Local).AddTicks(190),
                            LessonId = 9L,
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 299, DateTimeKind.Local).AddTicks(190),
                            UserId = 14L
                        },
                        new
                        {
                            UserLessonId = 22L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 299, DateTimeKind.Local).AddTicks(220),
                            LessonId = 10L,
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 299, DateTimeKind.Local).AddTicks(230),
                            UserId = 2L
                        },
                        new
                        {
                            UserLessonId = 23L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 299, DateTimeKind.Local).AddTicks(260),
                            LessonId = 10L,
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 299, DateTimeKind.Local).AddTicks(260),
                            UserId = 3L
                        },
                        new
                        {
                            UserLessonId = 24L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 299, DateTimeKind.Local).AddTicks(300),
                            LessonId = 11L,
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 299, DateTimeKind.Local).AddTicks(310),
                            UserId = 6L
                        },
                        new
                        {
                            UserLessonId = 25L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 299, DateTimeKind.Local).AddTicks(340),
                            LessonId = 11L,
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 299, DateTimeKind.Local).AddTicks(340),
                            UserId = 7L
                        },
                        new
                        {
                            UserLessonId = 26L,
                            CreatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 299, DateTimeKind.Local).AddTicks(370),
                            LessonId = 12L,
                            UpdatedDate = new DateTime(2019, 4, 14, 16, 27, 1, 299, DateTimeKind.Local).AddTicks(370),
                            UserId = 4L
                        });
                });

            modelBuilder.Entity("DPA.Model.UserLogEntity", b =>
                {
                    b.Property<long>("UserLogId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .HasMaxLength(8000);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<DateTime>("DateTime");

                    b.Property<int>("LogType");

                    b.Property<DateTime>("UpdatedDate");

                    b.Property<long>("UserId");

                    b.HasKey("UserLogId");

                    b.HasIndex("UserId");

                    b.ToTable("UsersLog","User");
                });

            modelBuilder.Entity("DPA.Model.ConstraintEntity", b =>
                {
                    b.HasOne("DPA.Model.UserEntity", "User")
                        .WithMany("Constraints")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DPA.Model.DepartmentEntity", b =>
                {
                    b.HasOne("DPA.Model.FacultyEntity", "Faculty")
                        .WithMany("Departments")
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DPA.Model.UserEntity", "HeadOfDepartment")
                        .WithOne("Department")
                        .HasForeignKey("DPA.Model.DepartmentEntity", "HeadOfDepartmentId");
                });

            modelBuilder.Entity("DPA.Model.DepartmentLessonEntity", b =>
                {
                    b.HasOne("DPA.Model.DepartmentEntity", "Department")
                        .WithMany("DepartmentLessons")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DPA.Model.LessonEntity", "Lesson")
                        .WithMany("DepartmentLessons")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DPA.Model.LessonGroupEntity", b =>
                {
                    b.HasOne("DPA.Model.LessonEntity", "Lesson")
                        .WithMany("LessonGroups")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DPA.Model.LocationEntity", b =>
                {
                    b.HasOne("DPA.Model.FacultyEntity", "Faculty")
                        .WithMany("Locations")
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DPA.Model.SyllabusEntity", b =>
                {
                    b.HasOne("DPA.Model.DepartmentEntity", "Department")
                        .WithMany("Syllabus")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DPA.Model.TimeEntity", b =>
                {
                    b.HasOne("DPA.Model.UnitLessonEntity", "UnitLesson")
                        .WithMany("TimeEntities")
                        .HasForeignKey("UnitLessonId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DPA.Model.UnitLessonEntity", b =>
                {
                    b.HasOne("DPA.Model.LessonEntity", "Lesson")
                        .WithMany("UnitLessons")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DPA.Model.LocationEntity", "Location")
                        .WithMany("UnitLessons")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DPA.Model.SyllabusEntity", "Syllabus")
                        .WithMany("UnitLessons")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DPA.Model.UserEntity", "User")
                        .WithMany("UnitLessons")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DPA.Model.UserLessonEntity", b =>
                {
                    b.HasOne("DPA.Model.LessonEntity", "Lesson")
                        .WithMany("UserLessons")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DPA.Model.UserEntity", "User")
                        .WithMany("UserLessons")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DPA.Model.UserLogEntity", b =>
                {
                    b.HasOne("DPA.Model.UserEntity", "User")
                        .WithMany("UsersLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
