// <auto-generated />
using System;
using DPA.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DPA.Database.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DPA.Model.ConstraintEntity", b =>
                {
                    b.Property<long>("ConstraintId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("EducationType");

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsFreeDay");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<DateTime>("UpdatedDate");

                    b.Property<long>("UserId");

                    b.Property<int>("WeeklyHour");

                    b.HasKey("ConstraintId");

                    b.HasIndex("UserId");

                    b.ToTable("Constraint","User");

                    b.HasData(
                        new
                        {
                            ConstraintId = 1L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(1231),
                            Description = "Description",
                            EducationType = 1,
                            IsActive = true,
                            IsFreeDay = true,
                            Title = "Kısıt 1",
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(1233),
                            UserId = 2L,
                            WeeklyHour = 4
                        },
                        new
                        {
                            ConstraintId = 2L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(1650),
                            Description = "Description",
                            EducationType = 2,
                            IsActive = true,
                            IsFreeDay = true,
                            Title = "Kısıt 2",
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(1651),
                            UserId = 3L,
                            WeeklyHour = 6
                        },
                        new
                        {
                            ConstraintId = 3L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(1680),
                            Description = "Description",
                            EducationType = 3,
                            IsActive = true,
                            IsFreeDay = false,
                            Title = "Kısıt 3",
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(1680),
                            UserId = 4L,
                            WeeklyHour = 8
                        },
                        new
                        {
                            ConstraintId = 4L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(1694),
                            Description = "Description",
                            EducationType = 2,
                            IsActive = true,
                            IsFreeDay = true,
                            Title = "Kısıt 4",
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(1695),
                            UserId = 5L,
                            WeeklyHour = 10
                        },
                        new
                        {
                            ConstraintId = 5L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(1708),
                            Description = "Description",
                            EducationType = 1,
                            IsActive = true,
                            IsFreeDay = true,
                            Title = "Kısıt 5",
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(1709),
                            UserId = 6L,
                            WeeklyHour = 12
                        },
                        new
                        {
                            ConstraintId = 6L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(1726),
                            Description = "Description",
                            EducationType = 3,
                            IsActive = true,
                            IsFreeDay = false,
                            Title = "Kısıt 6",
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(1726),
                            UserId = 7L,
                            WeeklyHour = 14
                        },
                        new
                        {
                            ConstraintId = 7L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(1740),
                            Description = "Description",
                            EducationType = 2,
                            IsActive = true,
                            IsFreeDay = true,
                            Title = "Kısıt 7",
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(1741),
                            UserId = 8L,
                            WeeklyHour = 8
                        },
                        new
                        {
                            ConstraintId = 8L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(1754),
                            Description = "Description",
                            EducationType = 1,
                            IsActive = true,
                            IsFreeDay = true,
                            Title = "Kısıt 8",
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(1755),
                            UserId = 9L,
                            WeeklyHour = 10
                        },
                        new
                        {
                            ConstraintId = 9L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(1769),
                            Description = "Description",
                            EducationType = 3,
                            IsActive = true,
                            IsFreeDay = false,
                            Title = "Kısıt 9",
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(1770),
                            UserId = 10L,
                            WeeklyHour = 12
                        },
                        new
                        {
                            ConstraintId = 10L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(1784),
                            Description = "Description",
                            EducationType = 1,
                            IsActive = true,
                            IsFreeDay = true,
                            Title = "Kısıt 10",
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(1785),
                            UserId = 11L,
                            WeeklyHour = 12
                        },
                        new
                        {
                            ConstraintId = 11L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(1798),
                            Description = "Description",
                            EducationType = 2,
                            IsActive = true,
                            IsFreeDay = true,
                            Title = "Kısıt 11",
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(1799),
                            UserId = 12L,
                            WeeklyHour = 12
                        },
                        new
                        {
                            ConstraintId = 12L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(1813),
                            Description = "Description",
                            EducationType = 3,
                            IsActive = true,
                            IsFreeDay = false,
                            Title = "Kısıt 12",
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(1814),
                            UserId = 13L,
                            WeeklyHour = 16
                        },
                        new
                        {
                            ConstraintId = 13L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(1827),
                            Description = "Description",
                            EducationType = 3,
                            IsActive = true,
                            IsFreeDay = false,
                            Title = "Kısıt 13",
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(1828),
                            UserId = 14L,
                            WeeklyHour = 16
                        });
                });

            modelBuilder.Entity("DPA.Model.DepartmentEntity", b =>
                {
                    b.Property<long>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("DepartmentCode")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<long>("FacultyId");

                    b.Property<long?>("HeadOfDepartmentId");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<DateTime>("UpdatedDate");

                    b.HasKey("DepartmentId");

                    b.HasIndex("FacultyId");

                    b.HasIndex("HeadOfDepartmentId")
                        .IsUnique()
                        .HasFilter("[HeadOfDepartmentId] IS NOT NULL");

                    b.ToTable("Department","Faculty");

                    b.HasData(
                        new
                        {
                            DepartmentId = 1L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 989, DateTimeKind.Local).AddTicks(5341),
                            DepartmentCode = "BM310",
                            FacultyId = 1L,
                            HeadOfDepartmentId = 1L,
                            Title = "Bilgisayar Mühendisliği Bölümü",
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 989, DateTimeKind.Local).AddTicks(5343)
                        },
                        new
                        {
                            DepartmentId = 2L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 989, DateTimeKind.Local).AddTicks(6144),
                            DepartmentCode = "BM311",
                            FacultyId = 1L,
                            Title = "Bilişim Sistemleri Mühendisliği Bölümü",
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 989, DateTimeKind.Local).AddTicks(6145)
                        },
                        new
                        {
                            DepartmentId = 3L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 989, DateTimeKind.Local).AddTicks(6166),
                            DepartmentCode = "BM312",
                            FacultyId = 1L,
                            Title = "Yazılım Mühendisliği Bölümü",
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 989, DateTimeKind.Local).AddTicks(6167)
                        });
                });

            modelBuilder.Entity("DPA.Model.DepartmentLessonEntity", b =>
                {
                    b.Property<long>("DepartmentLessonId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<long>("DepartmentId");

                    b.Property<long>("LessonId");

                    b.Property<DateTime>("UpdatedDate");

                    b.HasKey("DepartmentLessonId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("LessonId");

                    b.ToTable("DepartmentLesson","Faculty");

                    b.HasData(
                        new
                        {
                            DepartmentLessonId = 1L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 989, DateTimeKind.Local).AddTicks(6942),
                            DepartmentId = 1L,
                            LessonId = 1L,
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 989, DateTimeKind.Local).AddTicks(6943)
                        },
                        new
                        {
                            DepartmentLessonId = 2L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 989, DateTimeKind.Local).AddTicks(7297),
                            DepartmentId = 1L,
                            LessonId = 2L,
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 989, DateTimeKind.Local).AddTicks(7297)
                        },
                        new
                        {
                            DepartmentLessonId = 3L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 989, DateTimeKind.Local).AddTicks(7318),
                            DepartmentId = 1L,
                            LessonId = 3L,
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 989, DateTimeKind.Local).AddTicks(7318)
                        },
                        new
                        {
                            DepartmentLessonId = 4L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 989, DateTimeKind.Local).AddTicks(7331),
                            DepartmentId = 1L,
                            LessonId = 4L,
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 989, DateTimeKind.Local).AddTicks(7332)
                        },
                        new
                        {
                            DepartmentLessonId = 5L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 989, DateTimeKind.Local).AddTicks(7345),
                            DepartmentId = 1L,
                            LessonId = 5L,
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 989, DateTimeKind.Local).AddTicks(7346)
                        },
                        new
                        {
                            DepartmentLessonId = 6L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 989, DateTimeKind.Local).AddTicks(7381),
                            DepartmentId = 1L,
                            LessonId = 6L,
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 989, DateTimeKind.Local).AddTicks(7381)
                        },
                        new
                        {
                            DepartmentLessonId = 7L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 989, DateTimeKind.Local).AddTicks(7395),
                            DepartmentId = 1L,
                            LessonId = 7L,
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 989, DateTimeKind.Local).AddTicks(7395)
                        },
                        new
                        {
                            DepartmentLessonId = 8L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 989, DateTimeKind.Local).AddTicks(7408),
                            DepartmentId = 1L,
                            LessonId = 8L,
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 989, DateTimeKind.Local).AddTicks(7409)
                        },
                        new
                        {
                            DepartmentLessonId = 9L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 989, DateTimeKind.Local).AddTicks(7422),
                            DepartmentId = 1L,
                            LessonId = 9L,
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 989, DateTimeKind.Local).AddTicks(7423)
                        },
                        new
                        {
                            DepartmentLessonId = 10L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 989, DateTimeKind.Local).AddTicks(7437),
                            DepartmentId = 1L,
                            LessonId = 10L,
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 989, DateTimeKind.Local).AddTicks(7437)
                        },
                        new
                        {
                            DepartmentLessonId = 11L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 989, DateTimeKind.Local).AddTicks(7450),
                            DepartmentId = 1L,
                            LessonId = 11L,
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 989, DateTimeKind.Local).AddTicks(7451)
                        },
                        new
                        {
                            DepartmentLessonId = 12L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 989, DateTimeKind.Local).AddTicks(7464),
                            DepartmentId = 1L,
                            LessonId = 12L,
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 989, DateTimeKind.Local).AddTicks(7465)
                        });
                });

            modelBuilder.Entity("DPA.Model.FacultyEntity", b =>
                {
                    b.Property<long>("FacultyId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("FacultyCode")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<DateTime>("UpdatedDate");

                    b.HasKey("FacultyId");

                    b.ToTable("Faculty","Faculty");

                    b.HasData(
                        new
                        {
                            FacultyId = 1L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 989, DateTimeKind.Local).AddTicks(2744),
                            FacultyCode = "BM310",
                            Title = "BİLGİSAYAR VE BİLİŞİM BİLİMLERİ FAKÜLTESİ",
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 989, DateTimeKind.Local).AddTicks(2746)
                        },
                        new
                        {
                            FacultyId = 2L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 989, DateTimeKind.Local).AddTicks(2918),
                            FacultyCode = "MF123",
                            Title = "Mühendislik Fakültesi",
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 989, DateTimeKind.Local).AddTicks(2919)
                        },
                        new
                        {
                            FacultyId = 3L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 989, DateTimeKind.Local).AddTicks(2938),
                            FacultyCode = "HKK112",
                            Title = "Hukuk Fakültesi",
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 989, DateTimeKind.Local).AddTicks(2938)
                        },
                        new
                        {
                            FacultyId = 4L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 989, DateTimeKind.Local).AddTicks(2952),
                            FacultyCode = "TKL423",
                            Title = "Teknoloji Fakültesi",
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 989, DateTimeKind.Local).AddTicks(2953)
                        });
                });

            modelBuilder.Entity("DPA.Model.LessonEntity", b =>
                {
                    b.Property<long>("LessonId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AKTS");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<int>("Credit");

                    b.Property<string>("LessonCode")
                        .IsRequired();

                    b.Property<int>("LessonType");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150);

                    b.Property<int>("SemesterType");

                    b.Property<DateTime>("UpdatedDate");

                    b.Property<int>("WeeklyHour");

                    b.HasKey("LessonId");

                    b.ToTable("Lesson","Faculty");

                    b.HasData(
                        new
                        {
                            LessonId = 1L,
                            AKTS = 4,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(5590),
                            Credit = 4,
                            LessonCode = "TUR 101",
                            LessonType = 1,
                            Name = "TÜRK DİLİ",
                            SemesterType = 1,
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(5592),
                            WeeklyHour = 4
                        },
                        new
                        {
                            LessonId = 2L,
                            AKTS = 6,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(6416),
                            Credit = 4,
                            LessonCode = "FIZ 111",
                            LessonType = 1,
                            Name = "FİZİK I",
                            SemesterType = 1,
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(6416),
                            WeeklyHour = 5
                        },
                        new
                        {
                            LessonId = 3L,
                            AKTS = 6,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(6449),
                            Credit = 4,
                            LessonCode = "MAT 111",
                            LessonType = 1,
                            Name = "MATEMATİK I",
                            SemesterType = 1,
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(6449),
                            WeeklyHour = 4
                        },
                        new
                        {
                            LessonId = 4L,
                            AKTS = 4,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(6467),
                            Credit = 2,
                            LessonCode = "MAT 113",
                            LessonType = 1,
                            Name = "LİNEER CEBİR",
                            SemesterType = 1,
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(6467),
                            WeeklyHour = 2
                        },
                        new
                        {
                            LessonId = 5L,
                            AKTS = 4,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(6483),
                            Credit = 2,
                            LessonCode = "BSM 101",
                            LessonType = 1,
                            Name = "BİLGİSAYAR MÜHENDİSLİĞİNE GİRİŞ",
                            SemesterType = 1,
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(6483),
                            WeeklyHour = 2
                        },
                        new
                        {
                            LessonId = 6L,
                            AKTS = 6,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(6502),
                            Credit = 4,
                            LessonCode = "BSM 103",
                            LessonType = 1,
                            Name = "PROGRAMLAMAYA GİRİŞ",
                            SemesterType = 1,
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(6503),
                            WeeklyHour = 4
                        },
                        new
                        {
                            LessonId = 7L,
                            AKTS = 4,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(6518),
                            Credit = 4,
                            LessonCode = "ING 190",
                            LessonType = 1,
                            Name = "İNGİLİZCE",
                            SemesterType = 2,
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(6519),
                            WeeklyHour = 4
                        },
                        new
                        {
                            LessonId = 8L,
                            AKTS = 6,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(6535),
                            Credit = 4,
                            LessonCode = "FIZ 112",
                            LessonType = 1,
                            Name = "FİZİK II",
                            SemesterType = 2,
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(6535),
                            WeeklyHour = 5
                        },
                        new
                        {
                            LessonId = 9L,
                            AKTS = 6,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(6551),
                            Credit = 4,
                            LessonCode = "MAT 112",
                            LessonType = 1,
                            Name = "MATEMATİK II",
                            SemesterType = 2,
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(6552),
                            WeeklyHour = 4
                        },
                        new
                        {
                            LessonId = 10L,
                            AKTS = 6,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(6569),
                            Credit = 4,
                            LessonCode = "BSM 102",
                            LessonType = 1,
                            Name = "NESNEYE DAYALI PROGRAMLAMA",
                            SemesterType = 2,
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(6570),
                            WeeklyHour = 4
                        },
                        new
                        {
                            LessonId = 11L,
                            AKTS = 4,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(6586),
                            Credit = 3,
                            LessonCode = "BSM 104",
                            LessonType = 1,
                            Name = "WEB TEKNOLOJİLERİ",
                            SemesterType = 2,
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(6587),
                            WeeklyHour = 3
                        },
                        new
                        {
                            LessonId = 12L,
                            AKTS = 4,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(6603),
                            Credit = 3,
                            LessonCode = "IST 108",
                            LessonType = 1,
                            Name = "OLASILIK VE İSTATİSTİK",
                            SemesterType = 2,
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(6603),
                            WeeklyHour = 3
                        });
                });

            modelBuilder.Entity("DPA.Model.LessonGroupEntity", b =>
                {
                    b.Property<long>("LessonGroupId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<int>("GroupType");

                    b.Property<long>("LessonId");

                    b.Property<DateTime>("UpdatedDate");

                    b.HasKey("LessonGroupId");

                    b.HasIndex("LessonId");

                    b.ToTable("LessonGroup","Faculty");

                    b.HasData(
                        new
                        {
                            LessonGroupId = 1L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(7560),
                            GroupType = 1,
                            LessonId = 1L,
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(7562)
                        },
                        new
                        {
                            LessonGroupId = 2L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(7715),
                            GroupType = 2,
                            LessonId = 1L,
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(7715)
                        },
                        new
                        {
                            LessonGroupId = 3L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(7732),
                            GroupType = 1,
                            LessonId = 2L,
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(7732)
                        },
                        new
                        {
                            LessonGroupId = 4L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(7752),
                            GroupType = 2,
                            LessonId = 2L,
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(7753)
                        },
                        new
                        {
                            LessonGroupId = 5L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(7766),
                            GroupType = 1,
                            LessonId = 3L,
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(7767)
                        },
                        new
                        {
                            LessonGroupId = 6L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(7783),
                            GroupType = 2,
                            LessonId = 3L,
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(7783)
                        },
                        new
                        {
                            LessonGroupId = 7L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(7796),
                            GroupType = 1,
                            LessonId = 4L,
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(7797)
                        },
                        new
                        {
                            LessonGroupId = 8L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(7810),
                            GroupType = 1,
                            LessonId = 5L,
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(7811)
                        },
                        new
                        {
                            LessonGroupId = 9L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(7823),
                            GroupType = 1,
                            LessonId = 6L,
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(7824)
                        },
                        new
                        {
                            LessonGroupId = 10L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(7838),
                            GroupType = 2,
                            LessonId = 6L,
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(7839)
                        },
                        new
                        {
                            LessonGroupId = 11L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(7852),
                            GroupType = 1,
                            LessonId = 7L,
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(7853)
                        },
                        new
                        {
                            LessonGroupId = 12L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(7866),
                            GroupType = 2,
                            LessonId = 7L,
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(7867)
                        },
                        new
                        {
                            LessonGroupId = 13L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(7880),
                            GroupType = 1,
                            LessonId = 8L,
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(7880)
                        },
                        new
                        {
                            LessonGroupId = 14L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(7893),
                            GroupType = 2,
                            LessonId = 8L,
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(7894)
                        },
                        new
                        {
                            LessonGroupId = 15L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(7907),
                            GroupType = 1,
                            LessonId = 9L,
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(7908)
                        },
                        new
                        {
                            LessonGroupId = 16L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(7921),
                            GroupType = 2,
                            LessonId = 9L,
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(7921)
                        },
                        new
                        {
                            LessonGroupId = 17L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(7934),
                            GroupType = 1,
                            LessonId = 10L,
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(7935)
                        },
                        new
                        {
                            LessonGroupId = 18L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(7949),
                            GroupType = 2,
                            LessonId = 10L,
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(7949)
                        },
                        new
                        {
                            LessonGroupId = 19L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(7962),
                            GroupType = 1,
                            LessonId = 11L,
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(7963)
                        },
                        new
                        {
                            LessonGroupId = 20L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(7975),
                            GroupType = 2,
                            LessonId = 11L,
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(7976)
                        },
                        new
                        {
                            LessonGroupId = 21L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(7988),
                            GroupType = 1,
                            LessonId = 12L,
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(7989)
                        },
                        new
                        {
                            LessonGroupId = 22L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(8001),
                            GroupType = 2,
                            LessonId = 12L,
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(8002)
                        });
                });

            modelBuilder.Entity("DPA.Model.LocationEntity", b =>
                {
                    b.Property<long>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<long>("FacultyId");

                    b.Property<string>("Title")
                        .IsRequired();

                    b.Property<DateTime>("UpdatedDate");

                    b.HasKey("LocationId");

                    b.HasIndex("FacultyId");

                    b.ToTable("Location","Faculty");

                    b.HasData(
                        new
                        {
                            LocationId = 1L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 989, DateTimeKind.Local).AddTicks(8537),
                            FacultyId = 1L,
                            Title = "1000",
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 989, DateTimeKind.Local).AddTicks(8540)
                        },
                        new
                        {
                            LocationId = 2L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 989, DateTimeKind.Local).AddTicks(9288),
                            FacultyId = 1L,
                            Title = "1001",
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 989, DateTimeKind.Local).AddTicks(9289)
                        },
                        new
                        {
                            LocationId = 3L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 989, DateTimeKind.Local).AddTicks(9311),
                            FacultyId = 1L,
                            Title = "1002",
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 989, DateTimeKind.Local).AddTicks(9312)
                        },
                        new
                        {
                            LocationId = 4L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 989, DateTimeKind.Local).AddTicks(9327),
                            FacultyId = 1L,
                            Title = "1003",
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 989, DateTimeKind.Local).AddTicks(9328)
                        },
                        new
                        {
                            LocationId = 5L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 989, DateTimeKind.Local).AddTicks(9342),
                            FacultyId = 1L,
                            Title = "1004",
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 989, DateTimeKind.Local).AddTicks(9343)
                        },
                        new
                        {
                            LocationId = 6L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 989, DateTimeKind.Local).AddTicks(9360),
                            FacultyId = 1L,
                            Title = "1005",
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 989, DateTimeKind.Local).AddTicks(9361)
                        },
                        new
                        {
                            LocationId = 7L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 989, DateTimeKind.Local).AddTicks(9375),
                            FacultyId = 1L,
                            Title = "1006",
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 989, DateTimeKind.Local).AddTicks(9376)
                        },
                        new
                        {
                            LocationId = 8L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 989, DateTimeKind.Local).AddTicks(9390),
                            FacultyId = 1L,
                            Title = "1007",
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 989, DateTimeKind.Local).AddTicks(9391)
                        },
                        new
                        {
                            LocationId = 9L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 989, DateTimeKind.Local).AddTicks(9405),
                            FacultyId = 1L,
                            Title = "1008",
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 989, DateTimeKind.Local).AddTicks(9406)
                        },
                        new
                        {
                            LocationId = 10L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 989, DateTimeKind.Local).AddTicks(9431),
                            FacultyId = 1L,
                            Title = "1009",
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 989, DateTimeKind.Local).AddTicks(9431)
                        },
                        new
                        {
                            LocationId = 11L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 989, DateTimeKind.Local).AddTicks(9446),
                            FacultyId = 1L,
                            Title = "10010",
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 989, DateTimeKind.Local).AddTicks(9447)
                        },
                        new
                        {
                            LocationId = 12L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 989, DateTimeKind.Local).AddTicks(9461),
                            FacultyId = 1L,
                            Title = "10011",
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 989, DateTimeKind.Local).AddTicks(9462)
                        },
                        new
                        {
                            LocationId = 13L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 989, DateTimeKind.Local).AddTicks(9476),
                            FacultyId = 1L,
                            Title = "10012",
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 989, DateTimeKind.Local).AddTicks(9476)
                        },
                        new
                        {
                            LocationId = 14L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 989, DateTimeKind.Local).AddTicks(9490),
                            FacultyId = 1L,
                            Title = "10013",
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 989, DateTimeKind.Local).AddTicks(9491)
                        },
                        new
                        {
                            LocationId = 15L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 989, DateTimeKind.Local).AddTicks(9505),
                            FacultyId = 1L,
                            Title = "10014",
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 989, DateTimeKind.Local).AddTicks(9506)
                        },
                        new
                        {
                            LocationId = 16L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 989, DateTimeKind.Local).AddTicks(9520),
                            FacultyId = 1L,
                            Title = "10015",
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 989, DateTimeKind.Local).AddTicks(9521)
                        },
                        new
                        {
                            LocationId = 17L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 989, DateTimeKind.Local).AddTicks(9535),
                            FacultyId = 1L,
                            Title = "10016",
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 989, DateTimeKind.Local).AddTicks(9536)
                        },
                        new
                        {
                            LocationId = 18L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 989, DateTimeKind.Local).AddTicks(9551),
                            FacultyId = 1L,
                            Title = "10017",
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 989, DateTimeKind.Local).AddTicks(9552)
                        });
                });

            modelBuilder.Entity("DPA.Model.SyllabusEntity", b =>
                {
                    b.Property<long>("SyllabusId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<long>("DepartmentId");

                    b.Property<int>("EducationType");

                    b.Property<int>("PeriodType");

                    b.Property<int>("SemesterType");

                    b.Property<DateTime>("UpdatedDate");

                    b.Property<int>("WeeklyHour");

                    b.Property<int>("Year");

                    b.HasKey("SyllabusId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Syllabus","Syllabus");
                });

            modelBuilder.Entity("DPA.Model.TimeEntity", b =>
                {
                    b.Property<long>("TimeId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<int>("DayOfTheWeekType");

                    b.Property<int>("EndTime");

                    b.Property<int>("StarTime");

                    b.Property<long>("UnitLessonId");

                    b.Property<DateTime>("UpdatedDate");

                    b.HasKey("TimeId");

                    b.HasIndex("UnitLessonId");

                    b.ToTable("Time","Syllabus");
                });

            modelBuilder.Entity("DPA.Model.UnitLessonEntity", b =>
                {
                    b.Property<long>("UnitLessonId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<long>("LessonId");

                    b.Property<long>("LocationId");

                    b.Property<long>("SyllabusId");

                    b.Property<DateTime>("UpdatedDate");

                    b.Property<long>("UserId");

                    b.HasKey("UnitLessonId");

                    b.HasIndex("LessonId");

                    b.HasIndex("UserId");

                    b.ToTable("UnitLesson","Syllabus");
                });

            modelBuilder.Entity("DPA.Model.UserEntity", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(300);

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<int>("Roles");

                    b.Property<int>("Status");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<int>("Title");

                    b.Property<DateTime>("UpdatedDate");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("User","User");

                    b.HasData(
                        new
                        {
                            UserId = 1L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 985, DateTimeKind.Local).AddTicks(8862),
                            Email = "administrator@administrator.com",
                            Login = "1h0ATANFe6x7kMHo1PURE74WI0ayevUwfK/+Ie+IWX/xWrFWngcVUwL/ewryn38EMVMQBFaNo4SaVwgXaBWnDw==",
                            Name = "Administrator",
                            Password = "CkcVGgdOYzq3tr7Wqrckq73c0yUPgKBrxhKiM6kHgFEB8kQbWykm5UzorIz7wHS7elZ0iDBIffCVkdvhZ+gA9g==",
                            Roles = 3,
                            Status = 1,
                            Surname = "Administrator",
                            Title = 0,
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 985, DateTimeKind.Local).AddTicks(8881)
                        },
                        new
                        {
                            UserId = 2L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 987, DateTimeKind.Local).AddTicks(7451),
                            Email = "celalceken@sakarya.edu.tr",
                            Login = "sqqdGm+QyoYM0p0Co1hgYX9aPayWbuCoIpPkN3vm+ntuFm8/mNW901g1mPJP0V/ZdOuD05U5btfuffNNkvRSMQ==",
                            Name = "Celal",
                            Password = "CkcVGgdOYzq3tr7Wqrckq73c0yUPgKBrxhKiM6kHgFEB8kQbWykm5UzorIz7wHS7elZ0iDBIffCVkdvhZ+gA9g==",
                            Roles = 1,
                            Status = 1,
                            Surname = "Çeken",
                            Title = 1,
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 987, DateTimeKind.Local).AddTicks(7452)
                        },
                        new
                        {
                            UserId = 3L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 987, DateTimeKind.Local).AddTicks(7636),
                            Email = "coz@sakarya.edu.tr",
                            Login = "lpe17pCaWVWNiI8dXvCHIEgaSpoTiULAZbWhSDxk1zbEdv3je87szjOl8CFst+hU8hITlcCc2AtvEIAdxgA+ng==",
                            Name = "Cemil",
                            Password = "CkcVGgdOYzq3tr7Wqrckq73c0yUPgKBrxhKiM6kHgFEB8kQbWykm5UzorIz7wHS7elZ0iDBIffCVkdvhZ+gA9g==",
                            Roles = 2,
                            Status = 1,
                            Surname = "Öz",
                            Title = 1,
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 987, DateTimeKind.Local).AddTicks(7637)
                        },
                        new
                        {
                            UserId = 4L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 987, DateTimeKind.Local).AddTicks(7696),
                            Email = "umit@sakarya.edu.tr",
                            Login = "aYoce2dux8eT5/nvryziC97/nrEiqS5+S0hEMEvKhB0fGnI8dbF7AFLAi/+6dnvNOZwnHDJi+9VQwUtKaPeEcA==",
                            Name = "Ümit",
                            Password = "CkcVGgdOYzq3tr7Wqrckq73c0yUPgKBrxhKiM6kHgFEB8kQbWykm5UzorIz7wHS7elZ0iDBIffCVkdvhZ+gA9g==",
                            Roles = 1,
                            Status = 1,
                            Surname = "Kocabıçak",
                            Title = 1,
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 987, DateTimeKind.Local).AddTicks(7697)
                        },
                        new
                        {
                            UserId = 5L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 987, DateTimeKind.Local).AddTicks(7753),
                            Email = "azengin@sakarya.edu.tr",
                            Login = "3b8hL6Cd/mm0v6MgNvkKvnoUjLbK/8+JNw/0AIXmtZjxfOcpZYndmXqV8UHH4dI8b1EnJ4LZWNs8lQV74pv2jQ==",
                            Name = "Ahmet",
                            Password = "CkcVGgdOYzq3tr7Wqrckq73c0yUPgKBrxhKiM6kHgFEB8kQbWykm5UzorIz7wHS7elZ0iDBIffCVkdvhZ+gA9g==",
                            Roles = 1,
                            Status = 1,
                            Surname = "Zengin",
                            Title = 3,
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 987, DateTimeKind.Local).AddTicks(7754)
                        },
                        new
                        {
                            UserId = 6L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 987, DateTimeKind.Local).AddTicks(7815),
                            Email = "ozmen@sakarya.edu.tr",
                            Login = "DQFv5btLPxS0XrNFtrqeFiKSgPMPHwmrdk88CVFWmRBn2jK6vVpms4u8MoLUCvNMEhI99ECRDR8Rh6kuwDy+Zg==",
                            Name = "Ahmet",
                            Password = "CkcVGgdOYzq3tr7Wqrckq73c0yUPgKBrxhKiM6kHgFEB8kQbWykm5UzorIz7wHS7elZ0iDBIffCVkdvhZ+gA9g==",
                            Roles = 1,
                            Status = 1,
                            Surname = "Özmen",
                            Title = 3,
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 987, DateTimeKind.Local).AddTicks(7816)
                        },
                        new
                        {
                            UserId = 7L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 987, DateTimeKind.Local).AddTicks(7871),
                            Email = "cbayilmis@sakarya.edu.tr",
                            Login = "dOGHhzh1rEnqFOee38OOgEWmQM5Ex3+PtVwdLHWpKNlAjyuX+Zx9m91+f4TmlpEZKHL1hK/SunceSqkZ+m/u2g==",
                            Name = "Cüneyt",
                            Password = "CkcVGgdOYzq3tr7Wqrckq73c0yUPgKBrxhKiM6kHgFEB8kQbWykm5UzorIz7wHS7elZ0iDBIffCVkdvhZ+gA9g==",
                            Roles = 1,
                            Status = 1,
                            Surname = "Bayılmış",
                            Title = 3,
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 987, DateTimeKind.Local).AddTicks(7871)
                        },
                        new
                        {
                            UserId = 8L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 987, DateTimeKind.Local).AddTicks(7933),
                            Email = "ahmetarslan@sakarya.edu.tr",
                            Login = "h0g/LYGJK7QP9Lo3ZNMnCtlyzkVTVhf3c+S+lA7ExZ/U9XP+84SvRNjjmnYrCMKQS2r6D7TPuuHH75zNwTU4YQ==",
                            Name = "Ahmet",
                            Password = "CkcVGgdOYzq3tr7Wqrckq73c0yUPgKBrxhKiM6kHgFEB8kQbWykm5UzorIz7wHS7elZ0iDBIffCVkdvhZ+gA9g==",
                            Roles = 1,
                            Status = 1,
                            Surname = "Arslan",
                            Title = 2,
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 987, DateTimeKind.Local).AddTicks(7934)
                        },
                        new
                        {
                            UserId = 9L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 987, DateTimeKind.Local).AddTicks(7988),
                            Email = "beken@sakarya.edu.tr",
                            Login = "1J8MNqnuIyH/yRYMDQUejip91vrhoW+A3YdeD9eAYDtLuWx17l706wt6sXrzabpaW6CePiIxw5YU8jDQqnhMmA==",
                            Name = "Beyza",
                            Password = "CkcVGgdOYzq3tr7Wqrckq73c0yUPgKBrxhKiM6kHgFEB8kQbWykm5UzorIz7wHS7elZ0iDBIffCVkdvhZ+gA9g==",
                            Roles = 1,
                            Status = 1,
                            Surname = "Eken",
                            Title = 2,
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 987, DateTimeKind.Local).AddTicks(7989)
                        },
                        new
                        {
                            UserId = 10L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 987, DateTimeKind.Local).AddTicks(8045),
                            Email = "ddural@sakarya.edu.tr",
                            Login = "+tqmuZBVWUcLTVBaSyXnHUGxLiN8+kdgrkW2Ds9wxhS4wAC/NO+vSPFKLYoWHkZDvtP6gVUSfW77X9FkB/Bimw==",
                            Name = "Deniz",
                            Password = "CkcVGgdOYzq3tr7Wqrckq73c0yUPgKBrxhKiM6kHgFEB8kQbWykm5UzorIz7wHS7elZ0iDBIffCVkdvhZ+gA9g==",
                            Roles = 1,
                            Status = 1,
                            Surname = "Balta",
                            Title = 2,
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 987, DateTimeKind.Local).AddTicks(8046)
                        },
                        new
                        {
                            UserId = 11L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 987, DateTimeKind.Local).AddTicks(8099),
                            Email = "oguz@sakarya.edu.tr",
                            Login = "N2dbG766DJ+GQaFDlEPrH3ioi+ZD9VpnVGVHCtTxZl9nC+ruFrcTi7zgOIydZKCFaBqwKxpowNV2GYBRSPvNbQ==",
                            Name = "Oguzhan",
                            Password = "CkcVGgdOYzq3tr7Wqrckq73c0yUPgKBrxhKiM6kHgFEB8kQbWykm5UzorIz7wHS7elZ0iDBIffCVkdvhZ+gA9g==",
                            Roles = 1,
                            Status = 1,
                            Surname = "Aydın",
                            Title = 4,
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 987, DateTimeKind.Local).AddTicks(8100)
                        },
                        new
                        {
                            UserId = 12L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 987, DateTimeKind.Local).AddTicks(8158),
                            Email = "hasantutan@sakarya.edu.tr",
                            Login = "GgWLS/9l9VKx7d18VXX+K3i3oJ6emqeCCniMnl6Gbg1cJftNXfCWUFao5OpNTaWCw39B/Z/1E5vV2+PPDFFesQ==",
                            Name = "Hasan",
                            Password = "CkcVGgdOYzq3tr7Wqrckq73c0yUPgKBrxhKiM6kHgFEB8kQbWykm5UzorIz7wHS7elZ0iDBIffCVkdvhZ+gA9g==",
                            Roles = 1,
                            Status = 1,
                            Surname = "Tutan",
                            Title = 4,
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 987, DateTimeKind.Local).AddTicks(8159)
                        },
                        new
                        {
                            UserId = 13L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 987, DateTimeKind.Local).AddTicks(8214),
                            Email = "ercanpala@sakarya.edu.tr",
                            Login = "PS+3mJHvWnYUHEhmnfo8APwTthPB92Bf2CDAupt1vAWgbc78SYmxb+wL48kZAUB6jHANlNfpH9yuAjRAyF6vlA==",
                            Name = "Ercan",
                            Password = "CkcVGgdOYzq3tr7Wqrckq73c0yUPgKBrxhKiM6kHgFEB8kQbWykm5UzorIz7wHS7elZ0iDBIffCVkdvhZ+gA9g==",
                            Roles = 1,
                            Status = 1,
                            Surname = "Palabıyık",
                            Title = 4,
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 987, DateTimeKind.Local).AddTicks(8215)
                        },
                        new
                        {
                            UserId = 14L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 987, DateTimeKind.Local).AddTicks(8267),
                            Email = "meltemayy@sakarya.edu.tr",
                            Login = "Ee6akHsxZOrmTyxqSHZL9vRY+MZdM6mUeRwEc7K+dRE8k1k0qagjmU8MN7KF0yVy7EkplM/ZIx90EbzYa4vTdA==",
                            Name = "Meltem",
                            Password = "CkcVGgdOYzq3tr7Wqrckq73c0yUPgKBrxhKiM6kHgFEB8kQbWykm5UzorIz7wHS7elZ0iDBIffCVkdvhZ+gA9g==",
                            Roles = 1,
                            Status = 1,
                            Surname = "Aydın",
                            Title = 4,
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 987, DateTimeKind.Local).AddTicks(8268)
                        });
                });

            modelBuilder.Entity("DPA.Model.UserLessonEntity", b =>
                {
                    b.Property<long>("UserLessonId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<long>("LessonId");

                    b.Property<DateTime>("UpdatedDate");

                    b.Property<long>("UserId");

                    b.HasKey("UserLessonId");

                    b.HasIndex("LessonId");

                    b.HasIndex("UserId");

                    b.ToTable("UserLesson","User");

                    b.HasData(
                        new
                        {
                            UserLessonId = 1L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(9123),
                            LessonId = 1L,
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(9125),
                            UserId = 5L
                        },
                        new
                        {
                            UserLessonId = 2L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(9671),
                            LessonId = 1L,
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(9672),
                            UserId = 8L
                        },
                        new
                        {
                            UserLessonId = 3L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(9692),
                            LessonId = 1L,
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(9693),
                            UserId = 11L
                        },
                        new
                        {
                            UserLessonId = 4L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(9706),
                            LessonId = 2L,
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(9707),
                            UserId = 2L
                        },
                        new
                        {
                            UserLessonId = 5L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(9721),
                            LessonId = 2L,
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(9721),
                            UserId = 9L
                        },
                        new
                        {
                            UserLessonId = 6L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(9737),
                            LessonId = 2L,
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(9737),
                            UserId = 12L
                        },
                        new
                        {
                            UserLessonId = 7L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(9750),
                            LessonId = 3L,
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(9751),
                            UserId = 3L
                        },
                        new
                        {
                            UserLessonId = 8L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(9764),
                            LessonId = 3L,
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(9764),
                            UserId = 5L
                        },
                        new
                        {
                            UserLessonId = 9L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(9777),
                            LessonId = 3L,
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(9778),
                            UserId = 13L
                        },
                        new
                        {
                            UserLessonId = 10L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(9802),
                            LessonId = 4L,
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(9802),
                            UserId = 14L
                        },
                        new
                        {
                            UserLessonId = 11L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(9816),
                            LessonId = 5L,
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(9817),
                            UserId = 7L
                        },
                        new
                        {
                            UserLessonId = 12L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(9830),
                            LessonId = 6L,
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(9831),
                            UserId = 4L
                        },
                        new
                        {
                            UserLessonId = 13L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(9843),
                            LessonId = 6L,
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(9844),
                            UserId = 10L
                        },
                        new
                        {
                            UserLessonId = 14L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(9857),
                            LessonId = 7L,
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(9857),
                            UserId = 11L
                        },
                        new
                        {
                            UserLessonId = 15L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(9870),
                            LessonId = 7L,
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(9871),
                            UserId = 12L
                        },
                        new
                        {
                            UserLessonId = 16L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(9884),
                            LessonId = 7L,
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(9884),
                            UserId = 10L
                        },
                        new
                        {
                            UserLessonId = 17L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(9897),
                            LessonId = 8L,
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(9898),
                            UserId = 5L
                        },
                        new
                        {
                            UserLessonId = 18L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(9913),
                            LessonId = 8L,
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(9914),
                            UserId = 13L
                        },
                        new
                        {
                            UserLessonId = 19L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(9927),
                            LessonId = 9L,
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(9928),
                            UserId = 8L
                        },
                        new
                        {
                            UserLessonId = 20L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(9941),
                            LessonId = 9L,
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(9942),
                            UserId = 9L
                        },
                        new
                        {
                            UserLessonId = 21L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(9955),
                            LessonId = 9L,
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(9955),
                            UserId = 14L
                        },
                        new
                        {
                            UserLessonId = 22L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(9968),
                            LessonId = 10L,
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(9968),
                            UserId = 2L
                        },
                        new
                        {
                            UserLessonId = 23L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(9981),
                            LessonId = 10L,
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(9982),
                            UserId = 3L
                        },
                        new
                        {
                            UserLessonId = 24L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(9995),
                            LessonId = 11L,
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 988, DateTimeKind.Local).AddTicks(9995),
                            UserId = 6L
                        },
                        new
                        {
                            UserLessonId = 25L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 989, DateTimeKind.Local).AddTicks(8),
                            LessonId = 11L,
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 989, DateTimeKind.Local).AddTicks(8),
                            UserId = 7L
                        },
                        new
                        {
                            UserLessonId = 26L,
                            CreatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 989, DateTimeKind.Local).AddTicks(21),
                            LessonId = 12L,
                            UpdatedDate = new DateTime(2019, 4, 15, 22, 7, 12, 989, DateTimeKind.Local).AddTicks(22),
                            UserId = 4L
                        });
                });

            modelBuilder.Entity("DPA.Model.UserLogEntity", b =>
                {
                    b.Property<long>("UserLogId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .HasMaxLength(8000);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<DateTime>("DateTime");

                    b.Property<int>("LogType");

                    b.Property<DateTime>("UpdatedDate");

                    b.Property<long>("UserId");

                    b.HasKey("UserLogId");

                    b.HasIndex("UserId");

                    b.ToTable("UsersLog","User");
                });

            modelBuilder.Entity("DPA.Model.ConstraintEntity", b =>
                {
                    b.HasOne("DPA.Model.UserEntity", "User")
                        .WithMany("Constraints")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DPA.Model.DepartmentEntity", b =>
                {
                    b.HasOne("DPA.Model.FacultyEntity", "Faculty")
                        .WithMany("Departments")
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DPA.Model.UserEntity", "HeadOfDepartment")
                        .WithOne("Department")
                        .HasForeignKey("DPA.Model.DepartmentEntity", "HeadOfDepartmentId");
                });

            modelBuilder.Entity("DPA.Model.DepartmentLessonEntity", b =>
                {
                    b.HasOne("DPA.Model.DepartmentEntity", "Department")
                        .WithMany("DepartmentLessons")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DPA.Model.LessonEntity", "Lesson")
                        .WithMany("DepartmentLessons")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DPA.Model.LessonGroupEntity", b =>
                {
                    b.HasOne("DPA.Model.LessonEntity", "Lesson")
                        .WithMany("LessonGroups")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DPA.Model.LocationEntity", b =>
                {
                    b.HasOne("DPA.Model.FacultyEntity", "Faculty")
                        .WithMany("Locations")
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DPA.Model.SyllabusEntity", b =>
                {
                    b.HasOne("DPA.Model.DepartmentEntity", "Department")
                        .WithMany("Syllabus")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DPA.Model.TimeEntity", b =>
                {
                    b.HasOne("DPA.Model.UnitLessonEntity", "UnitLesson")
                        .WithMany("TimeEntities")
                        .HasForeignKey("UnitLessonId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DPA.Model.UnitLessonEntity", b =>
                {
                    b.HasOne("DPA.Model.LessonEntity", "Lesson")
                        .WithMany("UnitLessons")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DPA.Model.LocationEntity", "Location")
                        .WithMany("UnitLessons")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DPA.Model.SyllabusEntity", "Syllabus")
                        .WithMany("UnitLessons")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DPA.Model.UserEntity", "User")
                        .WithMany("UnitLessons")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DPA.Model.UserLessonEntity", b =>
                {
                    b.HasOne("DPA.Model.LessonEntity", "Lesson")
                        .WithMany("UserLessons")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DPA.Model.UserEntity", "User")
                        .WithMany("UserLessons")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DPA.Model.UserLogEntity", b =>
                {
                    b.HasOne("DPA.Model.UserEntity", "User")
                        .WithMany("UsersLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
